-- --------------------------------------------------------
-- Διακομιστής:                  127.0.0.1
-- Έκδοση διακομιστή:            11.4.0-MariaDB - mariadb.org binary distribution
-- Λειτ. σύστημα διακομιστή:     Win64
-- HeidiSQL Έκδοση:              12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for cooking
CREATE DATABASE IF NOT EXISTS `cooking` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;
USE `cooking`;

-- Dumping structure for πίνακας cooking.ingredients
CREATE TABLE IF NOT EXISTS `ingredients` (
  `ingredient_name` varchar(50) NOT NULL,
  `calories_per_gram` int(11) DEFAULT NULL,
  `group_name` enum('Vegetables','Fruits','Cereal and Potatoes','Milk and Dairy Products','Legumes','Red Meat','White Meat','Eggs','Fish and Seafood','Added fats and oils, olives and nuts') DEFAULT NULL,
  PRIMARY KEY (`ingredient_name`),
  KEY `food_groups_fk_3` (`group_name`),
  CONSTRAINT `food_groups_fk_3` FOREIGN KEY (`group_name`) REFERENCES `food_groups` (`group_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table cooking.ingredients: ~173 rows (approximately)
INSERT INTO `ingredients` (`ingredient_name`, `calories_per_gram`, `group_name`) VALUES
	('Apple', 1, 'Fruits'),
	('Apples', 1, 'Fruits'),
	('Avocado', 4, 'Fruits'),
	('Bacon', 5, 'Red Meat'),
	('Baguette', 2, 'Cereal and Potatoes'),
	('Balsamic glaze', 1, 'Added fats and oils, olives and nuts'),
	('Basil leaves', 1, 'Vegetables'),
	('Basmati rice', 2, 'Cereal and Potatoes'),
	('BBQ Sauce', 2, 'Added fats and oils, olives and nuts'),
	('Bean sprouts', 1, 'Vegetables'),
	('Beef', 3, 'Red Meat'),
	('Beef broth', 3, 'Red Meat'),
	('Beer', 4, 'Added fats and oils, olives and nuts'),
	('Bell peppers', 1, 'Vegetables'),
	('Berbere Spice', 0, NULL),
	('Black beans', 3, 'Legumes'),
	('Black olives', 5, 'Added fats and oils, olives and nuts'),
	('Black vinegar', 1, NULL),
	('Bonito flakes', 0, 'Fish and Seafood'),
	('Breadcrumbs', 1, 'Cereal and Potatoes'),
	('Brown sugar', 4, 'Added fats and oils, olives and nuts'),
	('Bulgur wheat', 1, 'Cereal and Potatoes'),
	('Butter', 7, 'Added fats and oils, olives and nuts'),
	('Cabbage', 0, 'Vegetables'),
	('Carrot', 1, 'Vegetables'),
	('Carrots', 1, 'Vegetables'),
	('Cashews', 6, 'Added fats and oils, olives and nuts'),
	('Celery', 0, 'Vegetables'),
	('Cheese', 4, 'Milk and Dairy Products'),
	('Chicken', 3, 'White Meat'),
	('Chickpeas', 3, 'Legumes'),
	('Chocolate Sprinkles', 4, 'Added fats and oils, olives and nuts'),
	('Chorizo', 3, 'Red Meat'),
	('Cilantro', 0, 'Vegetables'),
	('Cinnamon Stick', 0, NULL),
	('Clarified Butter', 7, 'Added fats and oils, olives and nuts'),
	('Cocoa powder', 3, 'Added fats and oils, olives and nuts'),
	('Coconut milk', 5, 'Milk and Dairy Products'),
	('Condensed Milk', 4, 'Milk and Dairy Products'),
	('Cotija cheese', 4, 'Milk and Dairy Products'),
	('Cream', 5, 'Milk and Dairy Products'),
	('Cucumber', 1, 'Vegetables'),
	('Cumin', 1, NULL),
	('Curry powder', 1, NULL),
	('Dill', 1, 'Vegetables'),
	('Duck', 5, 'White Meat'),
	('Egg', 2, 'Eggs'),
	('Eggplant', 2, 'Vegetables'),
	('Eggs', 2, 'Eggs'),
	('Enchilada sauce', 2, 'Vegetables'),
	('Espresso', 1, 'Vegetables'),
	('Feta cheese', 4, 'Milk and Dairy Products'),
	('Fish', 4, 'Fish and Seafood'),
	('Flour', 1, 'Cereal and Potatoes'),
	('Fresh basil', 1, 'Vegetables'),
	('Galangal', 1, 'Vegetables'),
	('Garam masala', 3, 'Added fats and oils, olives and nuts'),
	('Garlic', 1, 'Vegetables'),
	('Garlic Powder', 3, NULL),
	('Ghee', 9, 'Added fats and oils, olives and nuts'),
	('Ginger', 1, 'Vegetables'),
	('Ginger garlic paste', 2, 'Vegetables'),
	('Gochugaru', 1, NULL),
	('Grand Marnier', 4, 'Added fats and oils, olives and nuts'),
	('Grape leaves', 1, 'Vegetables'),
	('Green chilies', 1, 'Vegetables'),
	('Green curry paste', 3, 'Added fats and oils, olives and nuts'),
	('Green onions', 1, 'Vegetables'),
	('Ground beef', 3, 'Red Meat'),
	('Ground lamb', 5, 'Red Meat'),
	('Ground pork', 4, 'White Meat'),
	('Heavy cream', 3, 'Milk and Dairy Products'),
	('Hoisin sauce', 3, 'Added fats and oils, olives and nuts'),
	('Kaffir lime leaves', 1, 'Vegetables'),
	('Kalamata olives', 5, 'Added fats and oils, olives and nuts'),
	('Kashmiri chili powder', 3, 'Added fats and oils, olives and nuts'),
	('Kasuri methi (dried fenugreek leaves)', 2, 'Vegetables'),
	('Ladyfingers', 3, 'Cereal and Potatoes'),
	('Lamb', 2, 'Red Meat'),
	('Lemon juice', 1, 'Fruits'),
	('Lemongrass', 1, 'Vegetables'),
	('Lime juice', 1, 'Fruits'),
	('Marsala wine', 3, 'Added fats and oils, olives and nuts'),
	('Mascarpone cheese', 4, 'Milk and Dairy Products'),
	('Milk', 1, 'Milk and Dairy Products'),
	('Mint', 0, 'Vegetables'),
	('Mint leaves', 0, 'Vegetables'),
	('Mirin', 1, NULL),
	('Mitmita Spice', 0, NULL),
	('Mixed greens', 1, 'Vegetables'),
	('Mixed vegetables', 0, 'Vegetables'),
	('Mozzarella cheese', 4, 'Milk and Dairy Products'),
	('Mushrooms', 1, 'Vegetables'),
	('Mustard', 2, 'Added fats and oils, olives and nuts'),
	('Napa Cabbage', 0, 'Vegetables'),
	('Noodles', 3, 'Cereal and Potatoes'),
	('Nori (seaweed)', 2, 'Fish and Seafood'),
	('Nutmeg', 1, 'Vegetables'),
	('Olive Oil', 9, 'Added fats and oils, olives and nuts'),
	('Onion', 1, 'Vegetables'),
	('Onion Powder', 3, NULL),
	('Onions', 0, 'Vegetables'),
	('Oranges', 1, 'Fruits'),
	('Paneer', 2, 'Milk and Dairy Products'),
	('Paneer cheese', 4, 'Milk and Dairy Products'),
	('Paprika', 0, NULL),
	('Parmesan cheese', 4, 'Milk and Dairy Products'),
	('Parsley', 0, 'Vegetables'),
	('Pasta', 4, 'Cereal and Potatoes'),
	('Peanuts', 6, 'Added fats and oils, olives and nuts'),
	('Phyllo dough', 3, 'Cereal and Potatoes'),
	('Pickled Carrots', 1, 'Vegetables'),
	('Pickled ginger', 1, 'Vegetables'),
	('Pineapple', 3, 'Fruits'),
	('Pita chips', 3, 'Cereal and Potatoes'),
	('Pizza dough', 3, 'Cereal and Potatoes'),
	('Poblano peppers', 1, 'Vegetables'),
	('Pomegranate seeds', 1, 'Fruits'),
	('Pork', 3, 'White Meat'),
	('Pork Ribs', 3, 'Red Meat'),
	('Potato', 1, 'Cereal and Potatoes'),
	('Potatoes', 1, 'Cereal and Potatoes'),
	('Radishes', 1, 'Vegetables'),
	('Red bell pepper', 0, 'Vegetables'),
	('Red onion', 1, 'Vegetables'),
	('Red wine', 3, 'Added fats and oils, olives and nuts'),
	('Rice', 1, 'Cereal and Potatoes'),
	('Rice Noodles', 1, 'Cereal and Potatoes'),
	('Rice Paper', 1, 'Cereal and Potatoes'),
	('Rice vermicelli', 2, 'Cereal and Potatoes'),
	('Rice vinegar', 3, 'Added fats and oils, olives and nuts'),
	('Ricotta cheese', 2, 'Milk and Dairy Products'),
	('Saffron', 3, 'Added fats and oils, olives and nuts'),
	('Salsa', 0, NULL),
	('Salt', 0, NULL),
	('Seafood', 4, 'Fish and Seafood'),
	('Seaweed', 1, 'Vegetables'),
	('Sesame oil', 9, 'Added fats and oils, olives and nuts'),
	('Shrimp', 3, 'Fish and Seafood'),
	('Sichuan peppercorns', 6, 'Added fats and oils, olives and nuts'),
	('Silken tofu', 1, 'Vegetables'),
	('Soy Sauce', 2, 'Added fats and oils, olives and nuts'),
	('Spaghetti', 3, 'Cereal and Potatoes'),
	('Spinach', 1, 'Vegetables'),
	('Sugar', 4, NULL),
	('Sumac', 1, 'Vegetables'),
	('Tahini', 6, 'Added fats and oils, olives and nuts'),
	('Tamarind paste', 2, 'Fruits'),
	('Tandoori masala', 4, NULL),
	('Tapioca Flour', 1, 'Cereal and Potatoes'),
	('Teff Flour', 1, 'Cereal and Potatoes'),
	('Tempura batter', 4, 'Added fats and oils, olives and nuts'),
	('Thai basil', 1, 'Vegetables'),
	('Thai chilies', 1, 'Vegetables'),
	('Thyme', 1, 'Vegetables'),
	('Tofu', 2, 'Legumes'),
	('Tomato', 0, 'Vegetables'),
	('Tomato sauce', 2, 'Vegetables'),
	('Tomatoes', 2, 'Vegetables'),
	('Tortillas', 3, 'Cereal and Potatoes'),
	('Turmeric', 0, NULL),
	('Veal', 2, 'Red Meat'),
	('Veal shanks', 2, 'White Meat'),
	('Vegetables', 0, 'Vegetables'),
	('Vermicelli Noodles', 1, 'Cereal and Potatoes'),
	('Walnuts', 6, 'Added fats and oils, olives and nuts'),
	('Wasabi', 1, 'Vegetables'),
	('Water', 0, NULL),
	('White pepper', 3, NULL),
	('White wine', 1, NULL),
	('Yeast', 0, 'Cereal and Potatoes'),
	('Yogurt', 3, 'Milk and Dairy Products'),
	('Zucchini', 1, 'Vegetables');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;


clob 
blob