INSERT INTO recipes (recipe_name, short_desc, difficulty_level, prep_time, cooking_time, quantities, main_ingredient, tip1, tip2, tip3)
VALUES
('Spaghetti Carbonara', 'Classic Italian pasta dish', '3', '00:15:00', '00:20:00', 4, 'Spaghetti', 'Use fresh eggs', 'Keep in fridge for up to 3 days', NULL),
('Coq au Vin', 'Classic French chicken dish', '4', '00:20:00', '01:30:00', 6, 'Chicken', 'Marinate overnight for best flavor', 'Use a good quality red wine', NULL),
('Kung Pao Chicken', 'Popular Chinese stir-fry dish', '3', '00:15:00', '00:20:00', 4, 'Chicken', 'Prepare all ingredients before cooking', NULL, NULL),
('Chicken Tikka Masala', 'Iconic Indian curry dish', '3', '00:30:00', '00:30:00', 4, 'Chicken', 'Marinate chicken for at least 2 hours', NULL, NULL),
('Tacos al Pastor', 'Traditional Mexican street food', '2', '00:20:00', '00:30:00', 6, 'Pork', 'Use fresh pineapple for best taste', 'Grill meat for authentic flavor', NULL),
('Sushi Rolls', 'Japanese sushi rolls', '3', '00:45:00', '00:30:00', 4, 'Rice', 'Use sushi-grade fish', 'Keep hands wet to prevent sticking', NULL),
('Tom Yum Soup', 'Classic Thai spicy soup', '2', '00:15:00', '00:20:00', 4, 'Shrimp', 'Use fresh herbs for better flavor', NULL, NULL),
('Greek Salad', 'Traditional Greek salad', '1', '00:10:00', '00:00:00', 2, 'Tomato', 'Use fresh and ripe tomatoes', 'Add olives for extra flavor', NULL),
('Paella', 'Traditional Spanish rice dish', '4', '00:20:00', '00:30:00', 6, 'Rice', 'Use saffron for authentic taste', 'Cook rice evenly for best texture', 'Serve with lemon wedges'),
('Hummus', 'Classic Lebanese dip', '1', '00:10:00', '00:00:00', 4, 'Chickpeas', 'Use fresh lemon juice', 'Add a pinch of cumin for extra flavor', NULL),
('Margherita Pizza', 'Classic Italian pizza with tomato, mozzarella, and basil', '2', '00:20:00', '00:15:00', 4, 'Pizza dough', 'Use fresh basil leaves', 'Bake on a pizza stone for best results', NULL),
('Beef Bourguignon', 'French beef stew cooked in red wine', '4', '00:30:00', '02:30:00', 6, 'Beef', 'Use a good quality red wine', 'Cook slowly for tender meat', 'Serve with crusty bread'),
('Mapo Tofu', 'Spicy Chinese tofu dish with minced meat', '3', '00:20:00', '00:20:00', 4, 'Tofu', 'Use soft tofu for best texture', NULL, NULL),
('Chicken Biryani', 'Fragrant Indian rice dish with chicken and spices', '4', '00:30:00', '01:00:00', 6, 'Chicken', 'Marinate chicken for better flavor', 'Use basmati rice for best results', NULL),
('Guacamole', 'Mexican avocado dip with tomatoes and lime', '1', '00:15:00', '00:00:00', 4, 'Avocado', 'Use ripe avocados', 'Add lime juice to prevent browning', NULL),
('Tempura', 'Japanese deep-fried seafood and vegetables', '3', '00:20:00', '00:10:00', 4, 'Seafood', 'Use ice-cold batter for crispiness', 'Fry in small batches', NULL),
('Pad Thai', 'Classic Thai stir-fried noodle dish with shrimp', '3', '00:20:00', '00:15:00', 4, 'Noodles', 'Use tamarind paste for authentic taste', 'Add peanuts for extra crunch', NULL),
('Moussaka', 'Greek eggplant and lamb casserole with bechamel sauce', '4', '00:30:00', '01:00:00', 6, 'Eggplant', 'Let it rest before serving', NULL, NULL),
('Gazpacho', 'Traditional Spanish cold tomato soup', '1', '00:15:00', '00:00:00', 4, 'Tomato', 'Serve chilled', NULL, NULL),
('Falafel', 'Lebanese fried chickpea patties', '2', '00:20:00', '00:20:00', 4, 'Chickpeas', 'Use dried chickpeas soaked overnight', 'Add fresh herbs for better flavor', NULL),
('Lasagna', 'Classic Italian layered pasta dish with meat and cheese', '4', '00:30:00', '01:00:00', 6, 'Pasta', 'Use ricotta cheese for creaminess', 'Let it rest before serving', NULL),
('Ratatouille', 'French vegetable stew with tomatoes, eggplant, and zucchini', '3', '00:20:00', '00:40:00', 4, 'Vegetables', 'Use fresh vegetables', 'Serve with crusty bread', NULL),
('Peking Duck', 'Chinese roast duck dish with crispy skin', '5', '00:30:00', '02:00:00', 6, 'Duck', 'Air-dry duck for crispy skin', 'Serve with hoisin sauce', NULL),
('Palak Paneer', 'Indian spinach curry with paneer cheese', '3', '00:20:00', '00:30:00', 4, 'Spinach', 'Use fresh spinach', 'Add cream for richness', NULL),
('Chiles en Nogada', 'Mexican stuffed poblano peppers with walnut sauce', '4', '00:30:00', '00:45:00', 6, 'Poblano peppers', 'Use fresh pomegranates for garnish', 'Serve at room temperature', 'Use roasted walnuts for the sauce'),
('Sashimi', 'Japanese sliced raw fish dish', '3', '00:30:00', '00:00:00', 4, 'Fish', 'Use sushi-grade fish', 'Serve with soy sauce and wasabi', NULL),
('Tom Kha Gai', 'Thai coconut chicken soup with lemongrass and galangal', '2', '00:20:00', '00:20:00', 4, 'Chicken', 'Use fresh herbs for best flavor', NULL, NULL),
('Dolmades', 'Greek stuffed grape leaves with rice and herbs', '3', '00:30:00', '00:45:00', 6, 'Grape leaves', 'Use fresh grape leaves', 'Serve with lemon wedges', 'Add fresh dill for extra flavor'),
('Fattoush', 'Lebanese salad with mixed greens, vegetables, and pita chips', '2', '00:15:00', '00:00:00', 4, 'Mixed greens', 'Use toasted pita chips', 'Add sumac for extra tang', NULL),
('Carbonnade Flamande', 'Belgian beef and beer stew', '4', '00:30:00', '02:00:00', 6, 'Beef', 'Use Belgian beer for authenticity', 'Cook slowly for tender meat', NULL),
('Tiramisu', 'Classic Italian dessert with coffee-soaked ladyfingers and mascarpone', '2', '00:30:00', '00:00:00', 6, 'Ladyfingers', 'Use strong espresso', 'Chill overnight for best flavor', NULL),
('Crepes Suzette', 'French thin pancakes with orange sauce and Grand Marnier', '3', '00:15:00', '00:15:00', 4, 'Flour', 'Use fresh orange juice', 'Flambe with Grand Marnier', NULL),
('Kung Pao Shrimp', 'Chinese stir-fried shrimp dish with peanuts and chili peppers', '3', '00:15:00', '00:15:00', 4, 'Shrimp', 'Prepare all ingredients before cooking', 'Adjust spice level to taste', NULL),
('Butter Chicken', 'Indian creamy tomato-based chicken curry', '3', '00:20:00', '00:30:00', 4, 'Chicken', 'Marinate chicken for better flavor', 'Use fresh cream for richness', NULL),
('Enchiladas', 'Mexican rolled tortillas stuffed with meat and cheese, topped with sauce', '3', '00:20:00', '00:30:00', 4, 'Tortillas', 'Use fresh tortillas', 'Top with cheese and bake until bubbly', NULL),
('Tempura Vegetables', 'Japanese deep-fried battered vegetables', '2', '00:20:00', '00:10:00', 4, 'Vegetables', 'Use ice-cold batter for crispiness', 'Serve with tempura dipping sauce', NULL),
('Shakshuka', 'Middle Eastern poached eggs in spicy tomato sauce', '2', '00:15:00', '00:15:00', 4, 'Tomato', 'Use fresh tomatoes', 'Top with crumbled feta', NULL),
('Lamb Tagine', 'Moroccan slow-cooked lamb stew with spices and dried fruits', '4', '00:20:00', '02:00:00', 6, 'Lamb', 'Use a tagine pot for best results', 'Cook slowly for tender meat', 'Serve with couscous'),
('Tortilla Española', 'Spanish potato omelette', '2', '00:10:00', '00:30:00', 4, 'Potato', 'Use waxy potatoes', 'Let it cool before serving', NULL),
('Thai Green Curry', 'Thai spicy coconut milk-based curry with chicken and vegetables', '3', '00:20:00', '00:30:00', 4, 'Chicken', 'Use fresh lemongrass', 'Serve with jasmine rice', NULL),
('Spanakopita', 'Greek spinach and feta cheese pie in phyllo pastry', '3', '00:30:00', '00:30:00', 6, 'Spinach', 'Use fresh spinach', 'Brush phyllo with melted butter', NULL),
('Tabbouleh', 'Lebanese parsley and bulgur wheat salad with tomatoes and mint', '2', '00:15:00', '00:00:00', 4, 'Parsley', 'Use fresh mint leaves', 'Chill before serving', NULL),
('Osso Buco', 'Italian braised veal shanks with vegetables and white wine', '4', '00:30:00', '02:00:00', 6, 'Veal', 'Cook slowly for tender meat', 'Serve with gremolata', 'Pair with a glass of white wine'),
('Hot and Sour Soup', 'Chinese spicy and tangy soup with mushrooms and tofu', '2', '00:20:00', '00:20:00', 4, 'Tofu', 'Use fresh tofu', NULL, NULL),
('Paneer Tikka', 'Indian grilled paneer cheese skewers with spices and vegetables', '3', '00:20:00', '00:15:00', 4, 'Paneer', 'Marinate paneer for at least 2 hours', 'Use skewers for grilling', NULL),
('Chilaquiles', 'Mexican tortilla casserole with salsa and cheese', '2', '00:20:00', '00:30:00', 4, 'Tortillas', 'Use fresh salsa', 'Top with sour cream and cheese', NULL),
('Miso Soup', 'Japanese soup made with soybean paste, tofu, and seaweed', '2', '00:10:00', '00:10:00', 4, 'Tofu', 'Use miso paste for authentic flavor', 'Serve hot', NULL),
('Ceviche', 'Latin American seafood dish marinated in citrus juices', '2', '00:15:00', '00:00:00', 4, 'Fish', 'Use fresh lime juice', 'Serve chilled', NULL),
('Eggplant Parmesan', 'Italian baked eggplant dish with tomato sauce and cheese', '3', '00:30:00', '00:45:00', 4, 'Eggplant', 'Use fresh eggplants', 'Top with mozzarella cheese', NULL),
('Vietnamese Spring Rolls', 'Vietnamese rice paper rolls filled with shrimp, vegetables, and vermicelli noodles', '2', '00:30:00', '00:30:00', 4, 'Shrimp', 'Use fresh herbs for best flavor', 'Serve with dipping sauce', NULL),
('Chicken Korma', 'Indian chicken curry cooked with yogurt, cream, and spices', '3', '00:30:00', '00:45:00', 4, 'Chicken', 'Marinate chicken for better flavor', 'Use fresh cream for richness', NULL),
('Caprese Pizza', 'Italian pizza topped with tomatoes, mozzarella cheese, and basil', '2', '00:20:00', '00:15:00', 4, 'Pizza dough', 'Use fresh basil leaves', 'Top with fresh mozzarella', NULL),
('Gyoza', 'Japanese pan-fried dumplings filled with ground meat and vegetables', '3', '00:30:00', '00:20:00', 4, 'Pork', 'Use fresh ginger for better flavor', 'Serve with dipping sauce', NULL),
('Pasta Primavera', 'Italian pasta dish with fresh vegetables and Parmesan cheese', '2', '00:20:00', '00:20:00', 4, 'Pasta', 'Use seasonal vegetables', 'Top with grated Parmesan', NULL),
('Tofu Curry', 'Asian curry dish with tofu, vegetables, and coconut milk', '2', '00:25:00', '00:25:00', 4, 'Tofu', 'Use firm tofu', 'Serve with steamed rice', NULL),
('Pho', 'Traditional Vietnamese noodle soup with beef or chicken.', '3', '00:20:00', '02:00:00', 4, 'Beef', 'Use fresh herbs for garnish.', 'Serve with lime wedges.', NULL),
('Banh Mi', 'Vietnamese sandwich with pickled vegetables and meat.', '2', '00:15:00', '00:20:00', 2, 'Pork', 'Use a crusty baguette.', NULL, NULL),
('Spring Rolls', 'Fresh Vietnamese spring rolls with shrimp or pork.', '2', '00:30:00', '00:10:00', 4, 'Shrimp', 'Use fresh mint and cilantro.', 'Soak rice paper briefly.', NULL),
('Beef Stew', 'Hearty American beef stew with vegetables.', '3', '00:20:00', '03:00:00', 6, 'Beef', 'Brown the beef first.', 'Use red wine for depth of flavor.', NULL),
('Apple Pie', 'Classic American apple pie with a flaky crust.', '4', '00:30:00', '01:00:00', 8, 'Apple', 'Use a mix of sweet and tart apples.', 'Brush the crust with egg wash.', NULL),
('BBQ Ribs', 'American BBQ ribs with smoky flavor.', '3', '00:15:00', '03:00:00', 4, 'Pork Ribs', 'Marinate the ribs overnight.', NULL, NULL),
('Feijoada', 'Brazilian black bean stew with pork.', '3', '00:30:00', '02:30:00', 6, 'Black Beans', 'Use a variety of pork cuts.', 'Serve with orange slices.', 'Add a bay leaf for extra flavor.'),
('Pão de Queijo', 'Brazilian cheese bread.', '2', '00:15:00', '00:25:00', 24, 'Cheese', 'Use tapioca flour.', 'Grate the cheese finely.', NULL),
('Brigadeiro', 'Brazilian chocolate truffles.', '1', '00:10:00', '00:10:00', 20, 'Condensed Milk', 'Use good quality cocoa powder.', NULL, NULL),
('Kimchi', 'Spicy fermented Korean cabbage.', '3', '00:30:00', '00:00:00', 10, 'Cabbage', 'Use Korean chili powder.', 'Ferment for at least a week.', NULL),
('Bibimbap', 'Korean rice bowl with assorted toppings.', '3', '00:20:00', '00:30:00', 4, 'Rice', 'Use a variety of vegetables.', 'Serve with a fried egg on top.', 'Mix well before eating.'),
('Bulgogi', 'Korean marinated beef.', '2', '00:20:00', '00:15:00', 4, 'Beef', 'Marinate the beef overnight.', 'Cook on high heat.', 'Serve with rice and lettuce wraps.'),
('Doro Wat', 'Ethiopian spicy chicken stew.', '4', '00:20:00', '01:30:00', 6, 'Chicken', 'Use berbere spice mix.', 'Serve with injera.', NULL),
('Injera', 'Ethiopian sourdough flatbread.', '4', '00:10:00', '00:05:00', 12, 'Teff Flour', 'Ferment the batter for 3 days.', 'Cook on a hot griddle.', NULL),
('Kitfo', 'Ethiopian seasoned raw beef.', '3', '00:15:00', '00:00:00', 4, 'Beef', 'Use high-quality beef.', 'Serve with injera or bread.', NULL);
